import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { MainData } from '../models';

@Injectable({
  providedIn: 'root'
})
export class MainService {
  private boyData: MainData[] = [
    { id: 1, name: 'Александр', dName: 'Александровна', sName: 'Александрович' },
    { id: 2, name: 'Алексей', dName: 'Алексеевна', sName: 'Алексеевич' },
    { id: 3, name: 'Андрей', dName: 'Андреевна', sName: 'Андреевич' },
    { id: 4, name: 'Артем', dName: 'Артемовна', sName: 'Артемович' },
    { id: 5, name: 'Борис', dName: 'Борисовна', sName: 'Борисович' },
    { id: 6, name: 'Вадим', dName: 'Вадимовна', sName: 'Вадимович' },
    { id: 7, name: 'Валентин', dName: 'Валентиновна', sName: 'Валентинович' },
    { id: 8, name: 'Валерий', dName: 'Валерьевна', sName: 'Валерьевич' },
    { id: 9, name: 'Василий', dName: 'Васильевна', sName: 'Васильевич' },
    { id: 10, name: 'Виктор', dName: 'Викторовна', sName: 'Викторович' },
    { id: 11, name: 'Владимир', dName: 'Владимировна', sName: 'Владимирович' },
    { id: 12, name: 'Вячеслав', dName: 'Вячеславовна', sName: 'Вячеславович' },
    { id: 13, name: 'Георгий', dName: 'Георгиевна', sName: 'Георгиевич' },
    { id: 14, name: 'Григорий', dName: 'Григорьевна', sName: 'Григорьевич' },
    { id: 15, name: 'Даниил', dName: 'Данииловна', sName: 'Даниилович' },
    { id: 16, name: 'Денис', dName: 'Денисовна', sName: 'Денисович' },
    { id: 17, name: 'Дмитрий', dName: 'Дмитриевна', sName: 'Дмитриевич' },
    { id: 18, name: 'Евгений', dName: 'Евгеньевна', sName: 'Евгеньевич' },
    { id: 19, name: 'Егор', dName: 'Егоровна', sName: 'Егорович' },
    { id: 20, name: 'Иван', dName: 'Ивановна', sName: 'Иванович' },
    { id: 21, name: 'Игорь', dName: 'Игорьевна', sName: 'Игорьевич' },
    { id: 22, name: 'Илья', dName: 'Ильинична', sName: 'Ильич' },
    { id: 23, name: 'Кирилл', dName: 'Кирилловна', sName: 'Кириллович' },
    { id: 24, name: 'Константин', dName: 'Константиновна', sName: 'Константинович' },
    { id: 25, name: 'Максим', dName: 'Максимовна', sName: 'Максимович' },
    { id: 26, name: 'Марк', dName: 'Марковна', sName: 'Маркович' },
    { id: 27, name: 'Матвей', dName: 'Матвеевна', sName: 'Матвеевич' },
    { id: 28, name: 'Михаил', dName: 'Михайловна', sName: 'Михайлович' },
    { id: 29, name: 'Никита', dName: 'Никитична', sName: 'Никитович' },
    { id: 30, name: 'Николай', dName: 'Николаевна', sName: 'Николаевич' },
    { id: 31, name: 'Олег', dName: 'Олеговна', sName: 'Олегович' },
    { id: 32, name: 'Павел', dName: 'Павловна', sName: 'Павлович' },
    { id: 33, name: 'Петр', dName: 'Петровна', sName: 'Петрович' },
    { id: 34, name: 'Роман', dName: 'Романовна', sName: 'Романович' },
    { id: 35, name: 'Руслан', dName: 'Руслановна', sName: 'Русланович' },
    { id: 36, name: 'Сергей', dName: 'Сергеевна', sName: 'Сергеевич' },
    { id: 37, name: 'Станислав', dName: 'Станиславовна', sName: 'Станиславович' },
    { id: 38, name: 'Тимофей', dName: 'Тимофеевна', sName: 'Тимофеевич' },
    { id: 39, name: 'Тимур', dName: 'Тимуровна', sName: 'Тимурович' },
    { id: 40, name: 'Федор', dName: 'Федоровна', sName: 'Федорович' },
    { id: 41, name: 'Юрий', dName: 'Юрьевна', sName: 'Юрьевич' },
    { id: 42, name: 'Яков', dName: 'Якововна', sName: 'Якович' },
    { id: 43, name: 'Ярослав', dName: 'Ярославовна', sName: 'Ярославович' },
    { id: 44, name: 'Агафон', dName: 'Агафоновна', sName: 'Агафонович' },
    { id: 45, name: 'Аркадий', dName: 'Аркадьевна', sName: 'Аркадьевич' },
    { id: 46, name: 'Артём', dName: 'Артемовна', sName: 'Артемович' },
    { id: 47, name: 'Борислав', dName: 'Бориславовна', sName: 'Бориславович' },
    { id: 48, name: 'Вадим', dName: 'Вадимовна', sName: 'Вадимович' },
    { id: 49, name: 'Валентин', dName: 'Валентиновна', sName: 'Валентинович' },
    { id: 50, name: 'Валерий', dName: 'Валерьевна', sName: 'Валерьевич' },
    { id: 51, name: 'Василий', dName: 'Васильевна', sName: 'Васильевич' },
    { id: 52, name: 'Вениамин', dName: 'Вениаминовна', sName: 'Вениаминович' },
    { id: 53, name: 'Виктор', dName: 'Викторовна', sName: 'Викторович' },
    { id: 54, name: 'Виталий', dName: 'Витальевна', sName: 'Витальевич' },
    { id: 55, name: 'Владимир', dName: 'Владимировна', sName: 'Владимирович' },
    { id: 56, name: 'Владислав', dName: 'Владиславовна', sName: 'Владиславович' },
    { id: 57, name: 'Всеволод', dName: 'Всеволодовна', sName: 'Всеволодович' },
    { id: 58, name: 'Гавриил', dName: 'Гаврииловна', sName: 'Гавриилович' },
    { id: 59, name: 'Герман', dName: 'Германовна', sName: 'Германович' },
    { id: 60, name: 'Глеб', dName: 'Глебовна', sName: 'Глебович' },
    { id: 61, name: 'Григорий', dName: 'Григорьевна', sName: 'Григорьевич' },
    { id: 62, name: 'Давид', dName: 'Давидовна', sName: 'Давидович' },
    { id: 63, name: 'Дамир', dName: 'Дамировна', sName: 'Дамирович' },
    { id: 64, name: 'Даниил', dName: 'Данииловна', sName: 'Даниилович' },
    { id: 65, name: 'Данила', dName: 'Даниловна', sName: 'Данилович' },
    { id: 66, name: 'Демид', dName: 'Демидовна', sName: 'Демидович' },
    { id: 67, name: 'Демьян', dName: 'Демьяновна', sName: 'Демьянович' },
    { id: 68, name: 'Денис', dName: 'Денисовна', sName: 'Денисович' },
    { id: 69, name: 'Дмитрий', dName: 'Дмитриевна', sName: 'Дмитриевич' },
    { id: 70, name: 'Добрыня', dName: 'Добрыновна', sName: 'Добрынович' },
    { id: 71, name: 'Донат', dName: 'Донатовна', sName: 'Донатович' },
    { id: 72, name: 'Евгений', dName: 'Евгеньевна', sName: 'Евгеньевич' },
    { id: 73, name: 'Евдоким', dName: 'Евдокимовна', sName: 'Евдокимович' },
    { id: 74, name: 'Егор', dName: 'Егоровна', sName: 'Егорович' },
    { id: 75, name: 'Елисей', dName: 'Елисеевна', sName: 'Елисеевич' },
    { id: 76, name: 'Емельян', dName: 'Емельяновна', sName: 'Емельянович' },
    { id: 77, name: 'Еремей', dName: 'Еремеевна', sName: 'Еремеевич' },
    { id: 78, name: 'Ефим', dName: 'Ефимовна', sName: 'Ефимович' },
    { id: 79, name: 'Захар', dName: 'Захаровна', sName: 'Захарович' },
    { id: 80, name: 'Иван', dName: 'Ивановна', sName: 'Иванович' },
    { id: 81, name: 'Игнат', dName: 'Игнатовна', sName: 'Игнатович' },
    { id: 82, name: 'Игорь', dName: 'Игорьевна', sName: 'Игорьевич' },
    { id: 83, name: 'Иларион', dName: 'Иларионовна', sName: 'Иларионович' },
    { id: 85, name: 'Иннокентий', dName: 'Иннокентьевна', sName: 'Иннокентьевич' },
    { id: 86, name: 'Иосиф', dName: 'Иосифовна', sName: 'Иосифович' },
    { id: 87, name: 'Кирилл', dName: 'Кирилловна', sName: 'Кириллович' },
    { id: 88, name: 'Константин', dName: 'Константиновна', sName: 'Константинович' },
    { id: 89, name: 'Кузьма', dName: 'Кузьминична', sName: 'Кузьмич' },
    { id: 90, name: 'Лаврентий', dName: 'Лаврентьевна', sName: 'Лаврентьевич' },
    { id: 91, name: 'Лев', dName: 'Львовна', sName: 'Львович' },
    { id: 92, name: 'Леонид', dName: 'Леонидовна', sName: 'Леонидович' },
    { id: 93, name: 'Макар', dName: 'Макаровна', sName: 'Макарович' },
    { id: 95, name: 'Марат', dName: 'Маратовна', sName: 'Маратович' },
    { id: 96, name: 'Марк', dName: 'Марковна', sName: 'Маркович' },
    { id: 97, name: 'Матвей', dName: 'Матвеевна', sName: 'Матвеевич' },
    { id: 98, name: 'Мирон', dName: 'Мироновна', sName: 'Миронович' },
    { id: 99, name: 'Мирослав', dName: 'Мирославовна', sName: 'Мирославович' },
    { id: 100, name: 'Михаил', dName: 'Михайловна', sName: 'Михайлович' },
    { id: 101, name: 'Назар', dName: 'Назаровна', sName: 'Назарович' },
    { id: 102, name: 'Наиль', dName: 'Наильевна', sName: 'Наильевич' },
    { id: 103, name: 'Никита', dName: 'Никитична', sName: 'Никитович' },
    { id: 104, name: 'Николай', dName: 'Николаевна', sName: 'Николаевич' },
    { id: 106, name: 'Никон', dName: 'Никоновна', sName: 'Никонович' },
    { id: 107, name: 'Олег', dName: 'Олеговна', sName: 'Олегович' },
    { id: 108, name: 'Оскар', dName: 'Оскаровна', sName: 'Оскарович' },
    { id: 109, name: 'Павел', dName: 'Павловна', sName: 'Павлович' },
    { id: 110, name: 'Пётр', dName: 'Петровна', sName: 'Петрович' },
    { id: 111, name: 'Прохор', dName: 'Прохоровна', sName: 'Прохорович' },
    { id: 112, name: 'Радик', dName: 'Радиковна', sName: 'Радикович' },
    { id: 113, name: 'Радомир', dName: 'Радомировна', sName: 'Радомирович' },
    { id: 114, name: 'Ратмир', dName: 'Ратмировна', sName: 'Ратмирович' },
    { id: 115, name: 'Ринат', dName: 'Ринатовна', sName: 'Ринатович' },
    { id: 116, name: 'Роберт', dName: 'Робертовна', sName: 'Робертович' },
    { id: 117, name: 'Родион', dName: 'Родионовна', sName: 'Родионович' },
    { id: 118, name: 'Роман', dName: 'Романовна', sName: 'Романович' },
    { id: 119, name: 'Ростислав', dName: 'Ростиславовна', sName: 'Ростиславович' },
    { id: 120, name: 'Руслан', dName: 'Руслановна', sName: 'Русланович' },
    { id: 121, name: 'Савва', dName: 'Саввинична', sName: 'Саввинич' },
    { id: 122, name: 'Савелий', dName: 'Савелиевна', sName: 'Савелиевич' },
    { id: 123, name: 'Святослав', dName: 'Святославовна', sName: 'Святославович' },
    { id: 124, name: 'Семён', dName: 'Семёновна', sName: 'Семёнович' },
    { id: 125, name: 'Сергей', dName: 'Сергеевна', sName: 'Сергеевич' },
    { id: 126, name: 'Спартак', dName: 'Спартаковна', sName: 'Спартакович' },
    { id: 127, name: 'Станислав', dName: 'Станиславовна', sName: 'Станиславович' },
    { id: 128, name: 'Степан', dName: 'Степановна', sName: 'Степанович' },
    { id: 129, name: 'Тарас', dName: 'Тарасовна', sName: 'Тарасович' },
    { id: 130, name: 'Тимур', dName: 'Тимуровна', sName: 'Тимурович' },
    { id: 131, name: 'Тихон', dName: 'Тихоновна', sName: 'Тихонович' },
    { id: 132, name: 'Трифон', dName: 'Трифоновна', sName: 'Трифонович' },
    { id: 133, name: 'Трофим', dName: 'Трофимовна', sName: 'Трофимович' },
    { id: 134, name: 'Фадей', dName: 'Фадеевна', sName: 'Фадеевич' },
    { id: 135, name: 'Фёдор', dName: 'Федоровна', sName: 'Федорович' },
    { id: 136, name: 'Федот', dName: 'Федотовна', sName: 'Федотович' },
    { id: 137, name: 'Феликс', dName: 'Феликсовна', sName: 'Феликсович' },
    { id: 138, name: 'Филипп', dName: 'Филипповна', sName: 'Филиппович' },
    { id: 139, name: 'Эдуард', dName: 'Эдуардовна', sName: 'Эдуардович' },
    { id: 140, name: 'Эмиль', dName: 'Эмильевна', sName: 'Эмильевич' },
    { id: 141, name: 'Эрик', dName: 'Эриковна', sName: 'Эрикович' },
    { id: 142, name: 'Юлиан', dName: 'Юлиановна', sName: 'Юлианович' },
    { id: 144, name: 'Юрий', dName: 'Юрьевна', sName: 'Юрьевич' },
    { id: 145, name: 'Юстин', dName: 'Юстиновна', sName: 'Юстинович' },
    { id: 146, name: 'Яков', dName: 'Якововна', sName: 'Якович' },
    { id: 147, name: 'Ян', dName: 'Яновна', sName: 'Янович' },
    { id: 148, name: 'Ярослав', dName: 'Ярославовна', sName: 'Ярославович' }
  ];

  private girlData: MainData[] = [
    { name: "Юля", fullName: "Юлия", id: 1 },
    { name: "Аня", fullName: "Анна", id: 2 },
    { name: "Оля", fullName: "Ольга", id: 3 },
    { name: "Лена", fullName: "Елена", id: 4 },
    { name: "Катя", fullName: "Екатерина", id: 5 },
    { name: "Наташа", fullName: "Наталья", id: 6 },
    { name: "Марина", fullName: "Марина", id: 7 },
    { name: "Таня", fullName: "Татьяна", id: 8 },
    { name: "Ира", fullName: "Ирина", id: 9 },
    { name: "Вика", fullName: "Виктория", id: 10 },
    { name: "Света", fullName: "Светлана", id: 11 },
    { name: "Маша", fullName: "Мария", id: 12 },
    { name: "Юля", fullName: "Юлия", id: 13 },
    { name: "Алёна", fullName: "Алёна", id: 14 },
    { name: "Алла", fullName: "Алла", id: 15 },
    { name: "Алиса", fullName: "Алиса", id: 16 },
    { name: "Анастасия", fullName: "Анастасия", id: 17 },
    { name: "Валентина", fullName: "Валентина", id: 18 },
    { name: "Валерия", fullName: "Валерия", id: 19 },
    { name: "Вероника", fullName: "Вероника", id: 20 },
    { name: "Галина", fullName: "Галина", id: 21 },
    { name: "Дарья", fullName: "Дарья", id: 22 },
    { name: "Диана", fullName: "Диана", id: 23 },
    { name: "Евгения", fullName: "Евгения", id: 24 },
    { name: "Зоя", fullName: "Зоя", id: 25 },
    { name: "Зинаида", fullName: "Зинаида", id: 26 },
    { name: "Инна", fullName: "Инна", id: 27 },
    { name: "Карина", fullName: "Карина", id: 28 },
    { name: "Кира", fullName: "Кира", id: 29 },
    { name: "Кристина", fullName: "Кристина", id: 30 },
    { name: "Лариса", fullName: "Лариса", id: 31 },
    { name: "Любовь", fullName: "Любовь", id: 32 },
    { name: "Людмила", fullName: "Людмила", id: 33 },
    { name: "Маргарита", fullName: "Маргарита", id: 34 },
    { name: "Мирослава", fullName: "Мирослава", id: 35 },
    { name: "Надежда", fullName: "Надежда", id: 36 },
    { name: "Нина", fullName: "Нина", id: 37 },
    { name: "Оксана", fullName: "Оксана", id: 38 },
    { name: "Полина", fullName: "Полина", id: 39 },
    { name: "Раиса", fullName: "Раиса", id: 40 },
    { name: "Регина", fullName: "Регина", id: 41 },
    { name: "Римма", fullName: "Римма", id: 42 },
    { name: "София", fullName: "София", id: 43 },
    { name: "Стелла", fullName: "Стелла", id: 44 },
    { name: "Тамара", fullName: "Тамара", id: 45 },
    { name: "Эльвира", fullName: "Эльвира", id: 46 },
    { name: "Юлиана", fullName: "Юлиана", id: 47 },
    { name: "Таисия", fullName: "Таисия", id: 48 },
    { name: "Агата", fullName: "Агата", id: 49 },
    { name: "Яна", fullName: "Яна", id: 50 },
    { name: "Жанна", fullName: "Жанна", id: 51 },
    { name: "Лиана", fullName: "Лиана", id: 52 },
    { name: "Мирра", fullName: "Мирра", id: 53 },
    { name: "Софья", fullName: "Софья", id: 54 },
    { name: "Юлиана", fullName: "Юлиана", id: 55 },
    { name: "София", fullName: "София", id: 56 },
    { name: "Василиса", fullName: "Василиса", id: 57 },
    { name: "Лариса", fullName: "Лариса", id: 58 },
    { name: "Алиса", fullName: "Алиса", id: 59 },
    { name: "Инга", fullName: "Инга", id: 60 },
    { name: "Анисия", fullName: "Анисия", id: 61 },
    { name: "Елизавета", fullName: "Елизавета", id: 62 },
    { name: "Валентина", fullName: "Валентина", id: 63 },
    { name: "Эвелина", fullName: "Эвелина", id: 64 },
    { name: "Виктория", fullName: "Виктория", id: 65 },
    { name: "Лилия", fullName: "Лилия", id: 66 },
    { name: "Алина", fullName: "Алина", id: 67 },
    { name: "Вероника", fullName: "Вероника", id: 68 },
    { name: "Антонина", fullName: "Антонина", id: 69 },
    { name: "Ксения", fullName: "Ксения", id: 70 },
    { name: "Илона", fullName: "Илона", id: 71 },
    { name: "Карина", fullName: "Карина", id: 72 },
    { name: "Любовь", fullName: "Любовь", id: 73 },
    { name: "Виолетта", fullName: "Виолетта", id: 74 },
    { name: "Дарина", fullName: "Дарина", id: 75 },
    { name: "Пелагея", fullName: "Пелагея", id: 76 },
    { name: "Соня", fullName: "София", id: 77 },
    { name: "Марфа", fullName: "Марфа", id: 78 },
    { name: "Грета", fullName: "Грета", id: 79 },
    { name: "Тамара", fullName: "Тамара", id: 80 },
    { name: "Елена", fullName: "Елена", id: 81 },
    { name: "Агния", fullName: "Агния", id: 82 },
    { name: "Лариса", fullName: "Лариса", id: 83 },
    { name: "Дарья", fullName: "Дарья", id: 84 },
    { name: "Злата", fullName: "Злата", id: 85 },
    { name: "Мирослава", fullName: "Мирослава", id: 86 },
    { name: "Алина", fullName: "Алина", id: 87 },
    { name: "Лилия", fullName: "Лилия", id: 88 },
    { name: "Алиса", fullName: "Алиса", id: 89 },
    { name: "Юлиана", fullName: "Юлиана", id: 90 },
    { name: "Инга", fullName: "Инга", id: 91 },
    { name: "Марина", fullName: "Марина", id: 92 },
    { name: "Таисия", fullName: "Таисия", id: 93 },
    { name: "Эмилия", fullName: "Эмилия", id: 94 },
    { name: "Мирра", fullName: "Мирра", id: 95 },
    { name: "Антонина", fullName: "Антонина", id: 96 },
    { name: "Ксения", fullName: "Ксения", id: 97 },
    { name: "Вероника", fullName: "Вероника", id: 98 },
    { name: "Лисса", fullName: "Лисса", id: 99 },
    { name: "Ярослава", fullName: "Ярослава", id: 100 },
  ];

  constructor() {}

  public getData(isMan: boolean): Observable<MainData[]> {
    const data = isMan ? this.boyData : this.girlData;
    return of(this.uniqBy(data, 'name'));
  }

  private uniqBy(array: any[], key: any) {
    const seen = new Set();
    return array.filter((item) => {
      const value = typeof key === 'function' ? key(item) : item[key];
      if (seen.has(value)) {
        return false;
      } else {
        seen.add(value);
        return true;
      }
    });
  }
}
